- include_tasks: "install_{{ ansible_pkg_mgr }}.yaml"

- file:
    path: "~/.config/zsh"
    state: directory

- file:
    src: "{{ dotfiles_dir }}/zsh/{{ item }}"
    path: "~/.config/zsh/{{ item }}"
    state: link
  with_items:
    - .zprofile
    - .zshenv
    - .zshrc

- file:
    src: "{{ dotfiles_dir }}/zsh/{{ item }}"
    path: "~/{{ item }}"
    state: link
  with_items:
    - .zshenv

- file:
    path: "~/bin"
    state: directory
