plugins:
  "@textlint/text":
    extensions:
       - .org
rules:
  # https://github.com/textlint-ja/textlint-rule-preset-japanese
  preset-japanese:
    sentence-length: false
    no-dropping-the-ra: false
    no-doubled-joshi: false
    no-doubled-conjunctive-particle-ga: false
