- name: Set osx defaults
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  with_items:
    - domain: com.apple.finder
      key: AppleShowAllFiles
      type: bool
      value: TRUE
    - domain: com.apple.trackpad.scaling
      key:
      type: int
      value: 5
  when: ansible_distribution in ['MacOSX']
