# TODO: move to galaxy -> yhiraki.golang
- name: install golang
  shell: >
    ARCH=$(uname -sp |
      tr ' ' -  |
      tr [:upper:] [:lower:] |
      sed -e 's/x86_64/amd64/i' -e 's/arm/arm64/i')
    curl -L https://go.dev/dl/go{{ golang_version }}.${ARCH}.tar.gz |
    tar -C /usr/local -xzf -
  args:
    creates: /usr/local/go
  become: yes
