- name: Install git
  apt:
    pkg:
      - git

- name: Get git root directory
  shell: git rev-parse --show-toplevel
  register: gitroot
  ignore_errors: true
  changed_when: false

- name: Create .gitconfig and set .gitconfig.local
  shell: >
    git config
    --global include.path
    ~/.gitconfig.local
  args:
    creates: ~/.gitconfig

- name: Link git setting files
  file:
    src: "{{ gitroot.stdout }}/{{ item }}"
    path: "~/{{ item }}"
    state: link
  with_items:
    - .gitconfig.local
    - .gitexclude
