- name: install golang tools
  shell: go install {{ item.url }}
  with_items:
    - name: fzf
      url: github.com/junegunn/fzf@latest
    - name: ghq
      url: github.com/x-motemen/ghq@latest
  args:
    executable: zsh
    creates: $GOPATH/bin/{{ item.name }}

- name: install asdf
  git:
    repo: https://github.com/asdf-vm/asdf
    dest: $HOME/.asdf
    version: v0.11.3