- name: install golang tools
  shell: go install {{ item.url }}
  with_items:
    - name: fzf
      url: github.com/junegunn/fzf@latest
    - name: ghq
      url: github.com/x-motemen/ghq@latest
  args:
    executable: zsh
    creates: $GOPATH/bin/{{ item.name }}
