- name: Install build depends
  apt:
    pkg:
      - gcc
      - make
      - ncurses-dev

- name: Download emacs
  shell: |
    curl -L http://ftp.jaist.ac.jp/pub/GNU/emacs/emacs-{{ emacs_version }}.tar.gz |
    tar -xzf -
  args:
    chdir: "{{ work_dir }}"
    creates: "emacs-{{ emacs_version }}"

- name: Build emacs
  shell: |
    ./configure --prefix {{ install_prefix }}
    make
  args:
    chdir: "{{ work_dir }}/emacs-{{ emacs_version }}"
    creates: "src/emacs"

- name: Install emacs
  shell: |
    make install
  become: yes
  args:
    chdir: "{{ work_dir }}/emacs-{{ emacs_version }}"
    creates: "{{ install_prefix }}/bin/emacs"

- file:
    path: "~/.emacs.d"
    state: directory

- file:
    src: "{{ item }}"
    path: "~/.emacs.d/{{ item | basename }}"
    state: link
  with_fileglob:
    - "{{ gitroot.stdout }}/emacs/*"
